doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            custom_datetime: \Library\Circulation\Common\Infrastructure\Persistence\DoctrineTypes\DateTimeType
            date: \Library\Circulation\Common\Infrastructure\Persistence\DoctrineTypes\DateType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core'
                prefix: 'Library\Circulation\Core'
                alias: App
