# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Library\Circulation\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Common/Infrastructure/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Library\Circulation\Common\Infrastructure\Controller\:
        resource: '../src/Common/Infrastructure/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Library\Circulation\Common\Infrastructure\EventBus\OnKernelTerminate:
        tags:
            - { name: kernel.event_listener, event: kernel.terminate }

    Library\Circulation\UseCase\BookCheckOut\Application\BookCheckOutHandler:
        public: true
    Library\Circulation\Common\Application\Date\ClockInterface:
        public: true
    Library\Circulation\Core\Finance\Application\FinanceServiceInterface:
        alias: Library\Circulation\Core\Finance\Infrastructure\FinanceService
        public: true
    Library\Circulation\Core\LibraryCard\Application\LibraryCardPersistenceInterface:
        alias: Library\Circulation\Core\LibraryCard\Infrastructure\LibraryCardEntityPersistence
        public: true
    Library\Circulation\Core\OtherMaterial\Domain\Privilege\OtherMaterialPrivilegeBuilder:
        public: true
    Library\Circulation\Common\Domain\OtherMaterialBorrow\OtherMaterialBorrowPolicyBuilder:
        public: true
    Library\Circulation\Core\Satistics\Application\PatronBorrowedBooksStatisticsRepositoryInterface:
        alias: Library\Circulation\Core\Book\Infrastructure\BookEntityRepository
        public: true
    Library\Circulation\UseCase\BookCheckOut\Domain\BookCheckOutPolicy:
        public: true
    Library\Circulation\UseCase\OtherMaterialCheckOut\Domain\OtherMaterialCheckOutActionBuilderInterface:
        alias: Library\Circulation\UseCase\OtherMaterialCheckOut\Application\OtherMaterialCheckOutActionBuilder
        public: true
    Library\Circulation\Core\Satistics\Application\PatronBorrowedOtherMaterialsStatisticsRepositoryInterface:
        alias: Library\Circulation\Core\OtherMaterial\Infrastructure\OtherMaterialEntityRepository
        public: true
    Library\Circulation\UseCase\OtherMaterialUseInLibrary\Domain\OtherMaterialUseInLibraryActionBuilderInterface:
        alias: Library\Circulation\UseCase\OtherMaterialUseInLibrary\Application\OtherMaterialUseInLibraryActionBuilder
        public: true
    Library\Circulation\Core\BusinessHours\Domain\BusinessHoursServiceInterface:
        alias: Library\Circulation\Core\BusinessHours\Infrastructure\BusinessHoursService
        public: true
    Library\Circulation\UseCase\BookCheckIn\Domain\BookCheckInActionInterface:
        alias: Library\Circulation\UseCase\BookCheckIn\Application\BookCheckInAction
        public: true
    Library\Circulation\Common\Domain\DomainEvent\DomainEventDispatcher:
        arguments:
            $listenerProvider: '@Library\Circulation\Common\Domain\DomainEvent\DomainListenerProvider'
            $eventStore: '@Library\Circulation\Common\Domain\DomainEvent\DomainEventStore'
    Library\Circulation\Common\Domain\DomainEvent\DomainEventStore:
        public: true
    Library\Circulation\UseCase\BookCheckIn\Application\BookCheckInHandler:
        public: true


